export const staffs = [
  {
    url: "https://yuma-kitamura.nekohack.me/",
    x: "",
    github: "jiyuujin",
    displayName: "jiyuujin",
    avatar: "/staffs/jiyuujin.jpg",
  },
  {
    url: "",
    x: "is_ryo",
    github: "is_ryo",
    displayName: "is_ryo",
    avatar: "/staffs/is_ryo.png",
  },
  {
    url: "",
    x: "hai_haino",
    github: "haitak",
    displayName: "ハイノ",
    avatar: "/staffs/haino.png",
  },
  {
    url: "",
    x: "high_g_engineer",
    github: "highgrenade",
    displayName: "high-g",
    avatar: "/staffs/high-g.jpg",
  },
  {
    url: "",
    x: "torano_manji",
    github: "t_moarnaj_nio",
    displayName: "torano_tomo",
    avatar: "/staffs/torano_tomo.png",
  },
  {
    url: "",
    x: "31415O_Kyo",
    github: "0622okakyo",
    displayName: "okakyo",
    avatar: "/staffs/okakyo.jpeg",
  },
  {
    url: "",
    x: "ike_keichan",
    github: "",
    displayName: "Keisuke Ikeda",
    avatar: "/staffs/ike_keichan.png",
  },
  {
    url: "",
    x: "zonoryo03",
    github: "zonoryo03",
    displayName: "ぞのりょー",
    avatar: "/staffs/zonoryo03.jpg",
  },
  {
    url: "",
    x: "Michi_program",
    github: "",
    displayName: "Michi",
    avatar: "/staffs/michi.jpg",
  },
  {
    url: "https://github.com/azufb?tab=repositories",
    x: "azunyan_eng",
    github: "azufb",
    displayName: "あずにゃん",
    avatar: "/staffs/azunyan.jpg",
  },
  {
    url: "",
    x: "yh65743",
    github: "",
    displayName: "比嘉康至",
    avatar: "/staffs/higa.jpeg",
  },
  {
    url: "",
    x: "honchang_",
    github: "honchang",
    displayName: "honchang",
    avatar: "/staffs/honchang.jpg",
  },
  {
    url: "https://github.com/illionillion",
    x: "Sei_engineer",
    github: "illionillion",
    displayName: "一ノ瀬裕斗",
    avatar: "/staffs/dimyasvariant.jpg",
  },
  {
    url: "",
    x: "Ryuki_4648",
    github: "ryuki_s46",
    displayName: "yuki",
    avatar: "/staffs/yuki.jpg",
  },
  {
    url: "https://ikki418.hatenablog.jp/",
    x: "ikki418",
    github: "",
    displayName: "ikki418",
    avatar: "/staffs/ikki418.jpeg",
  },
  {
    url: "",
    x: "engineeryuki921",
    github: "",
    displayName: "むね (ゆき)",
    avatar: "/staffs/mune.png",
  },
  {
    url: "https://www.yahooshiken.com/",
    x: "ho460kenya",
    github: "yahooshiken",
    displayName: "Hoshi",
    avatar: "/staffs/hoshi.jpeg",
  },
  {
    url: "",
    x: "NandemoToken",
    github: "",
    displayName: "なんでもトークン",
    avatar: "/staffs/NandemoToken.png",
  },
  {
    url: "",
    x: "k1tikurisu",
    github: "",
    displayName: "daiki",
    avatar: "/staffs/daiki.jpeg",
  },
  {
    url: "https://github.com/yamasaw",
    x: "yamasaw44",
    github: "yamasaw",
    displayName: "yamasaw",
    avatar: "/staffs/yamasaw.jpg",
  },
  {
    url: "",
    x: "",
    github: "syun17",
    displayName: "シュンキ",
    avatar: "/staffs/shunki.jpg",
  },
];
