name: "Compare Screenshots"
description: "mainとfeatureのスクリーンショットを比較する"

inputs:
  working-directory:
    description: "The directory to run the action in"
    required: false
    default: "./apps/storybook"

runs:
  using: "composite"
  steps:
    - name: Check out code
      if: ${{ github.event_name != 'pull_request_target' }}
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Check out PR
      if: ${{ github.event_name == 'pull_request_target' }}
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        fetch-depth: 0

    - name: Download expected screenshots from artifact
      uses: actions/download-artifact@v4
      with:
        name: expected-screenshots
        path: ${{ inputs.working-directory }}/vrt-report/expected/
        working-directory: ${{ inputs.working-directory }}

    - name: Download actual screenshots from artifact
      uses: actions/download-artifact@v4
      with:
        name: actual-screenshots
        path: ${{ inputs.working-directory }}/__screenshots__
        working-directory: ${{ inputs.working-directory }}

    - name: Workaround for detached HEAD
      shell: bash
      run: git checkout ${GITHUB_HEAD_REF#refs/heads/} || git checkout -b ${GITHUB_HEAD_REF#refs/heads/} && git pull

    - name: Compare Screenshots
      shell: bash
      run: |
        pnpm install
        ls -la
        pnpm ci:vrt
      working-directory: ${{ inputs.working-directory }}

    - name: Check VRT report
      shell: bash
      run: |
        ls -la
        ls -la vrt-report
      working-directory: ${{ inputs.working-directory }}

    - name: Output Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: "vrt-report-artifact"
        path: ${{ inputs.working-directory }}/vrt-report

    - name: Find comment
      uses: peter-evans/find-comment@v3
      id: find_comment
      with:
        issue-number: ${{ github.event.pull_request.number }}
        comment-author: "github-actions[bot]"
        body-includes: reg-suit detected

    - name: Comment VRT report URL
      uses: peter-evans/create-or-update-comment@v4
      with:
        comment-id: ${{ steps.find_comment.outputs.comment-id }}
        issue-number: ${{ github.event.pull_request.number }}
        body: |
          reg-suit report
          https://staging.fec-kansai-2025.pages.dev/${{github.head_ref}}/vrt-report
        edit-mode: replace
