name: "Check Storybook Build"

description: "Check Storybook Build"

runs:
  using: "composite"
  defaults:
    run:
      shell: bash
      working-directory: ./apps/storybook
  steps:
    - name: Check out repository code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install dependencies
      uses: ./.github/actions/install-dependencies

    - name: Check Format And Linting
      run: pnpm check

    - name: Check Building Storybook
      run: pnpm build
