name: "Check Storybook Build"

description: "Check Storybook Build"

inputs:
  working-directory:
    description: "The directory to run the action in"
    required: false
    default: "./apps/storybook"

runs:
  using: "composite"
  steps:
    - name: Check out repository code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: InstallDependencies
      uses: ./.github/actions/install-dependencies
      with:
        working-directory: ${{ inputs.working-directory }}

    - name: Check EditorConfig
      shell: bash
      run: npx -y editorconfig-checker
      working-directory: ${{ inputs.working-directory }}

    - name: Check Format And Linting
      shell: bash
      run: pnpm check
      working-directory: ${{ inputs.working-directory }}

    - name: Build Storybook
      shell: bash
      run: pnpm build
      working-directory: ${{ inputs.working-directory }}

    - name: Upload Storybook Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: storybook-build-artifact
        path: ${{ inputs.working-directory }}/storybook-static
        retention-days: 1

    - name: Take Expected Screenshots (from main branch)
      uses: ./.github/actions/vrt/take-expected
      with:
        working-directory: ${{ inputs.working-directory }}

    - name: Take Actual Screenshots (from current branch)
      uses: ./.github/actions/vrt/take-actual
      with:
        working-directory: ${{ inputs.working-directory }}
