name: "Check Storybook Build"

description: "Check Storybook Build"

inputs:
  working-directory:
    description: "The directory to run the action in"
    required: false
    default: "./apps/storybook"

runs:
  using: "composite"
  steps:
    - name: Check out repository code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: InstallDependencies
      uses: ./.github/actions/install-dependencies
      with:
        working-directory: ${{ inputs.working-directory }}

    - name: Check EditorConfig
      shell: bash
      run: npx -y editorconfig-checker
      working-directory: ${{ inputs.working-directory }}

    - name: Check Format And Linting
      shell: bash
      run: pnpm check
      working-directory: ${{ inputs.working-directory }}

    - name: Restore cached expected screenshots # キャッシュに保存されたスクショがあったら再利用する
      id: expected_screenshots_cache
      uses: ./.github/actions/composite-screenshots/cache-screenshots

    - name: Restore or build storybook # キャッシュにスクショが保存されてなかったらStorybookをビルドしてスクショ撮影する
      if: ${{ steps.expected_screenshots_cache.outputs.cache-hit != 'true'}}
      uses: ./.github/actions/composite-screenshots/cache-storybook-static

    - name: workaround for detached HEAD
      shell: bash
      run: |
        git checkout ${GITHUB_REF#refs/pull/*/head} || git checkout -b ${GITHUB_REF#refs/pull/*/head} && git pull origin ${GITHUB_REF#refs/pull/*/head}

    - name: screenshot and visual regression test
      shell: bash
      run: |
        pnpm ci:screenshot
      working-directory: ${{ inputs.working-directory }}

    - name: Upload actual screenshots to artifact
      uses: actions/upload-artifact@v4
      with:
        name: actual-screenshots
        path: ${{ inputs.working-directory}}/__screenshots__
        retention-days: 3
