name: "Check UI Build"

description: "Check UI Build"

inputs:
  working-directory:
    description: "The directory to run the action in"
    required: false
    default: "./apps/web"

runs:
  using: "composite"
  steps:
    - name: Check out repository code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: InstallDependencies
      uses: ./.github/actions/install-dependencies
      with:
        working-directory: ${{ inputs.working-directory }}

    - name: Check Spelling
      shell: bash
      run: pnpm typecheck
      working-directory: ${{ inputs.working-directory }}

    - name: Check Format And Linting
      shell: bash
      run: pnpm check
      working-directory: ${{ inputs.working-directory }}

    - name: Check Building
      shell: bash
      run: pnpm build
      working-directory: ${{ inputs.working-directory }}

    - name: Output Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: "ui-build-artifact"
        path: ${{ inputs.working-directory }}/out
