name: "Check UI Build"

description: "Check UI Build"

runs:
  using: "composite"
  defaults:
    run:
      shell: bash
      working-directory: ./apps/web
  steps:
    - name: Check out repository code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Check Spelling
      run: pnpm typecheck

    - name: Check Format And Linting
      run: pnpm check

    - name: Check Building
      run: pnpm build
