name: "Check UI Build"

description: "Check UI Build"

runs:
  using: "composite"
  steps:
    - name: Check out repository code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install dependencies
      uses: ./.github/actions/install-dependencies

    - name: Move to Storybook directory
      run: cd apps/web

    - name: Check Spelling
      run: pnpm typecheck

    - name: Check Format And Linting
      run: pnpm check

    - name: Check Building
      run: pnpm build
