export const staffs = [
  {
    x: "",
    github: "jiyuujin",
    displayName: "jiyuujin",
    avatar: "jiyuujin.jpg",
  },
  {
    x: "is_ryo",
    github: "is_ryo",
    displayName: "is_ryo",
    avatar: "is_ryo.png",
  },
  {
    x: "hai_haino",
    github: "haitak",
    displayName: "ハイノ",
    avatar: "haino.png",
  },
  {
    x: "high_g_engineer",
    github: "highgrenade",
    displayName: "high-g",
    avatar: "high-g.jpg",
  },
  {
    x: "torano_manji",
    github: "t_moarnaj_nio",
    displayName: "torano_tomo",
    avatar: "torano_tomo.png",
  },
  {
    x: "31415O_Kyo",
    github: "0622okakyo",
    displayName: "okakyo",
    avatar: "okakyo.jpeg",
  },
  {
    x: "ike_keichan",
    github: "",
    displayName: "Keisuke Ikeda",
    avatar: "ike_keichan.png",
  },
  {
    x: "zonoryo03",
    github: "zonoryo03",
    displayName: "ぞのりょー",
    avatar: "zonoryo03.jpg",
  },
  {
    x: "Michi_program",
    github: "",
    displayName: "Michi",
    avatar: "michi.jpg",
  },
  {
    x: "azunyan_eng",
    github: "azufb",
    displayName: "あずにゃん",
    avatar: "azunyan.jpg",
  },
  {
    x: "yh65743",
    github: "",
    displayName: "比嘉康至",
    avatar: "higa.jpeg",
  },
  {
    x: "",
    github: "honchang",
    displayName: "honchang",
    avatar: "",
  },
  {
    x: "Sei_engineer",
    github: "illionillion",
    displayName: "一ノ瀬裕斗",
    avatar: "dimyasvariant.jpg",
  },
  {
    x: "Ryuki_4648",
    github: "ryuki_s46",
    displayName: "yuki",
    avatar: "yuki.jpg",
  },
  {
    x: "ikki418",
    github: "",
    displayName: "ikki418",
    avatar: "ikki418.jpeg",
  },
  {
    x: "engineeryuki921",
    github: "",
    displayName: "むね (ゆき)",
    avatar: "mune.png",
  },
  {
    x: "ho460kenya",
    github: "yahooshiken",
    displayName: "Hoshi",
    avatar: "hoshi.jpeg",
  },
  {
    x: "NandemoToken",
    github: "",
    displayName: "なんでもトークン",
    avatar: "NandemoToken.png",
  },
  {
    x: "k1tikurisu",
    github: "",
    displayName: "daiki",
    avatar: "daiki.jpeg",
  },
  {
    x: "",
    github: "yamasaw",
    displayName: "yamasaw",
    avatar: "",
  },
  {
    x: "",
    github: "syun17",
    displayName: "シュンキ",
    avatar: "shunki.jpg",
  },
];
