name: Take Actual Screenshots
description: "Take Actual Screenshots"

inputs:
  working-directory:
    description: "The directory to run the action in"
    required: false
    default: "./apps/storybook"

runs:
  using: "composite"
  steps:
    - name: Check out code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Client setup
      uses: ./.github/actions/install-dependencies
      with:
        working-directory: ${{ inputs.working-directory }}

    - name: Workaround for detached HEAD
      shell: bash
      run: |
        git checkout ${GITHUB_HEAD_REF#refs/heads/} || git checkout -b ${GITHUB_HEAD_REF#refs/heads/}
        git branch --set-upstream-to=origin/${GITHUB_HEAD_REF#refs/heads/} ${GITHUB_HEAD_REF#refs/heads/} || true
        git pull

    - name: Take actual screenshots
      shell: bash
      run: |
        # ビルドをスキップして、現在ブランチのスクリーンショットのみ撮影
        if [ ! -d "storybook-static" ]; then
          pnpm build
        fi
        PORT=9003 timeout 180s pnpm run ci:screenshot
        # プロセスクリーンアップ
        pkill -f "http-server" || true
        pkill -f "storycap" || true
      working-directory: ${{ inputs.working-directory }}

    - name: Upload actual screenshots to artifact
      uses: actions/upload-artifact@v4
      with:
        name: actual-screenshots
        path: ${{ inputs.working-directory }}/__screenshots__
        retention-days: 3
