name: Chekck Stage Build
on:
  # push:
  #   branches:
  #     - staging
  pull_request:
    branches:
      - staging
jobs:
  CheckUIBuild:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check EditorConfig
        uses: editorconfig-checker/action-editorconfig-checker@main

      - name: Check UI Build
        uses: ./.github/actions/check-ui-build
  CheckStoryBookBuild:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check Storybook Build
        uses: ./.github/actions/check-storybook-build

      - name: Restore cached expected screenshots # キャッシュに保存されたスクショがあったら再利用する
        id: expected_screenshots_cache
        uses: ./.github/actions/composite-screenshots/cache-screenshots

      - name: Restore or build storybook # キャッシュにスクショが保存されてなかったらStorybookをビルドしてスクショ撮影する
        if: ${{ steps.expected_screenshots_cache.outputs.cache-hit != 'true'}}
        uses: ./.github/actions/composite-screenshots/cache-storybook-static

      - name: workaround for detached HEAD
        shell: bash
        run: |
          git checkout ${GITHUB_REF#refs/pull/*/head} || git checkout -b ${GITHUB_REF#refs/pull/*/head} && git pull origin ${GITHUB_REF#refs/pull/*/head}

      - name: screenshot and visual regression test
        shell: bash
        run: |
          pnpm ci:screenshot
          pnpm ci:vrt

      - name: Upload actual screenshots to artifact
        uses: actions/upload-artifact@v4
        with:
          name: actual-screenshots
          path: __screenshots__
          retention-days: 3

      - name: Compare Screenshots
        uses: ./.github/actions/composite-screenshots/compare-screenshots

  Deploy:
    runs-on: ubuntu-latest
    needs: [CheckUIBuild, CheckStoryBookBuild]
    steps:
      - name: Make Deploy Directory
        shell: bash
        run: |
          ls -la
          mkdir -p ./_deploy

      - name: Download UI Artifacts
        uses: actions/download-artifact@v4
        with:
          name: ui-build-artifact
          path: ./_deploy

      - name: Download Storybook Artifacts
        uses: actions/download-artifact@v4
        with:
          name: storybook-build-artifact
          path: ./_deploy/storybook

      - name: Check Merged Artifacts
        shell: bash
        run: |
          ls -la ./_deploy

      - name: Publish to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy ./_deploy --project-name=fec-kansai-2025 --commit-dirty=true --branch=staging
