name: Chekck Production Build
on:
  push:
    tags:
      - "v*"
jobs:
  CheckUIBuild:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check UI Build
        uses: ./.github/actions/check-ui-build
  CheckStoryBookBuild:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check Storybook Build
        uses: ./.github/actions/check-storybook-build

  Deploy:
    runs-on: ubuntu-latest
    needs: [CheckUIBuild, CheckStoryBookBuild]
    steps:
      - name: Make Deploy Directory
        shell: bash
        run: |
          ls -la
          mkdir -p ./_deploy

      - name: Download UI Artifacts
        uses: actions/download-artifact@v4
        with:
          name: ui-build-artifact
          path: ./_deploy

      # - name: Download Storybook Artifacts
      #   uses: actions/download-artifact@v4
      #   with:
      #     name: storybook-build-artifact
      #     path: ./_deploy/storybook

      - name: Check Merged Artifacts
        shell: bash
        run: |
          ls -la

      # - name: Publish to Cloudflare Pages
      #   uses: cloudflare/pages-action@1
      #   with:
      #     accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      #     apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      #     projectName: fec-kansai-2025
      #     directory: ./_deploy
      #     gitHubToken: ${{ secrets.GITHUB_TOKEN }}
