name: Chekck Stage Build
on:
  # push:
  #   branches:
  #     - staging
  pull_request:
    branches:
      - staging

jobs:
  CheckUIBuild:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check UI Build
        uses: ./.github/actions/check-ui-build
  CheckStoryBookBuild:
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write
      issues: write
      contents: write
      actions: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check Storybook Build
        uses: ./.github/actions/check-storybook-build

      - name: Compare Screenshots
        uses: ./.github/actions/composite-screenshots/compare-screenshots
        with:
          github: ${{ toJson(github) }}

  Deploy:
    runs-on: ubuntu-latest
    needs: [CheckUIBuild, CheckStoryBookBuild]
    steps:
      - name: Make Deploy Directory
        shell: bash
        run: |
          ls -la
          mkdir -p ./_deploy

      - name: Download UI Artifacts
        uses: actions/download-artifact@v4
        with:
          name: ui-build-artifact
          path: ./_deploy

      - name: Download Storybook Artifacts
        uses: actions/download-artifact@v4
        with:
          name: storybook-build-artifact
          path: ./_deploy/storybook

      - name: Download VRT Artifacts
        uses: actions/download-artifact@v4
        with:
          name: vrt-report-artifact
          path: ./_deploy/${{github.head_ref}}/vrt-report

      - name: Check Merged Artifacts
        shell: bash
        run: |
          ls -la ./_deploy

      - name: Publish to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy ./_deploy --project-name=fec-kansai-2025 --commit-dirty=true --branch=staging
