name: Chekck Production Build
on:
  push:
    tags:
      - "v*"
    branches:
      - main

env:
  BASE_URL: ${{ vars.NEXT_PUBLIC_BASE_URL }}
  GTAG_ID: ${{ vars.NEXT_PUBLIC_GTAG_ID }}

jobs:
  CheckUIBuild:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check UI Build
        uses: ./.github/actions/check-ui-build
        with:
          next-public-base-url: ${{ env.BASE_URL }}
          next-public-gtag-id: ${{ env.GTAG_ID }}

  Deploy:
    runs-on: ubuntu-latest
    needs: [CheckUIBuild]
    steps:
      - name: Make Deploy Directory
        shell: bash
        run: |
          ls -la
          mkdir -p ./_deploy

      - name: Download UI Artifacts
        uses: actions/download-artifact@v4
        with:
          name: ui-build-artifact
          path: ./_deploy

      - name: Check Merged Artifacts
        shell: bash
        run: |
          ls -la

      - name: Publish to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy ./_deploy --project-name=fec-kansai-2025 --commit-dirty=true --branch=main
