name: Chekck Production Build
on:
  push:
    tags:
      - "v*"
jobs:
  CheckUIBuild:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check UI Build
        uses: ./.github/actions/check-ui-build
  CheckStoryBookBuild:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check UI Build
        uses: ./.github/actions/check-ui-build
